### ISSUE TITLE
Please add more comments to your code 

### ISSUE THREAD

**Issue by PlasmaDev5** [alan-jak/3D-Game-Engine-Editor#1]
please add more comments to code to that it is easier for me to read. At the moment i see alot of testing string but i am unsure on why without the comments.

thanks :)

**Comment by alan-jak** [comment]
I'll do it now

**Comment by alan-jak** [comment]
It's done, also, please consider changing the name from StringPhaser to StringParser, and I will upload the current GUI code later this week, after I implement the scenegraph tab. At that stage it will not have the ability to add GameObjects, save files, or add/remove components, it'll only be a basic GUI
