### ISSUE TITLE
Apache License 2.0

### ISSUE THREAD

**Issue by CelloCodez** [alan-jak/3D-Game-Engine-Editor#3]
Shouldn't this code be under the Apache License 2.0 like the original engine (if you go to BennyQBD on Github)? There should be a header for every file, with copyright info:(http://www.apache.org/licenses/LICENSE-2.0)

**Comment by alan-jak** [comment]
This was made using code from before he introduced the Apache License into the engine, about 90% of which I made myself following the videos. I asked Benny for a little clarification about whether or not I need the license.

**Comment by CelloCodez** [comment]
Ok. Imma close this issue
